# Dockerfile.dev
FROM node:22-alpine

WORKDIR /app

# Copy package manifests + Prisma schema first
COPY package.json pnpm-lock.yaml* ./
COPY prisma ./prisma

# Install dependencies
RUN corepack enable pnpm && pnpm install

# copy the rest of the app
COPY . .

EXPOSE 3000
CMD ["pnpm", "dev"]
